server {
    listen       3000;
    server_name  localhost;

    # 指向 dist 目录（使用 nginx -p 参数时，root 相对于 prefix 路径）
    root   dist;
    index  index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # 静态资源缓存
    location ~* \.(js|css|png|jpg|jpeg|svg|ico|woff|woff2|ttf|eot)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }

    error_page 404 /index.html;
}
